version: "3.8"
services:
  db14:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
    ports:
      - "5444:5432"
  app:
    build: .
    restart: always
    ports:
      - "3003:3000"
    depends_on:
      - db14
