name: "Push: main"

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  deploy_back:
    runs-on:
      - back-runner
    steps:
      - uses: actions/checkout@v3.3
      - name: Create .env file
        run: |
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> .env
          echo "DATABASE_PASS=${{ secrets.DATABASE_PASS }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "BACK_HOST=${{ secrets.BACK_HOST }}" >> .env
          echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> .env
      - name: Deploy dev
        run: docker-compose up -d --build
